[package]
name = "gamepad_mouse"
version = "2.0.0"
edition = "2021"

[dependencies]
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
enigo = { version = "0.3.0", features = ["wayland", "x11rb"], default-features = false }
gilrs = "0.11.0"
